version: "2.1"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "3000:3000"
